DROP TABLE IF EXISTS BLEATER_IDS;

CREATE TABLE BLEATER_IDS
(
  user_id int,
  bleater_id int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';

LOAD DATA
INPATH '/earcloud/bleater_ids_FULL.csv'
OVERWRITE INTO TABLE BLEATER_IDS;
